[package]
name = "tow_mater"
version = "0.1.0"
authors = []
edition = "2018"
build = "build.rs"

[dependencies]
rlbot = { path = "rlbot-rust" }
flatbuffers = "*"
na = { version = "*", package = "nalgebra" }

[build-dependencies]
chrono = "*"